version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.2.1
  kubernetes: circleci/kubernetes@1.3.1
  helm: circleci/helm@2.0.1

jobs:
  build:
    machine:
      image: ubuntu-2204:2022.10.1
      resource_class: large
    steps:
      - checkout
      - aws-ecr/build-image:
          push-image: false
          dockerfile: Dockerfile
          path: ./
          build-path: ./
          tag: "$CIRCLE_SHA1,$CIRCLE_TAG"
          repo: "$CIRCLE_PROJECT_REPONAME"
      - run:
          name: Save Docker image to export it to workspace
          command: |
            docker save $(docker image ls --format '{{.Repository}}:{{.Tag}}') > /tmp/simple-staking.tar
      - persist_to_workspace:
          root: /tmp
          paths:
            - simple-staking.tar

  push:
    machine:
      image: ubuntu-2204:2022.10.1
      resource_class: large
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Load Docker image from workspace
          command: |
            docker load -i /tmp/simple-staking.tar
      - aws-ecr/ecr-login:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          region: "$AWS_REGION"
      - aws-ecr/push-image:
          registry-id: AWS_ECR_REGISTRY_ID
          region: "$AWS_REGION"
          repo: "$CIRCLE_PROJECT_REPONAME"
          tag: "$CIRCLE_SHA1,$CIRCLE_TAG"

  deploy_staging:
    machine:
      image: ubuntu-2204:2024.01.1
      resource_class: large
    steps:
      - checkout
      - aws-ecr/ecr-login:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          region: "$AWS_REGION"
      - kubernetes/install-kubeconfig:
          kubeconfig: TESTNET_KUBECONFIG
      - helm/install-helm-client
      - run:
          name: Fetch and replace config placeholders from CircleCi env vars
          command: |
            HELM_VALUES=/home/circleci/project/.circleci/values-staging.yaml
            sed -i "s/API_STAGING_FQDN/$API_STAGING_FQDN/g" $HELM_VALUES
            sed -i "s/DASHBOARD_STAGING_FQDN/$DASHBOARD_STAGING_FQDN/g" $HELM_VALUES
      - run:
          name: Perform a dry run of the new release
          command: |
            helm upgrade --install --debug --dry-run \
              -n $DEPLOY_STAGING_NAMESPACE \
              --values /home/circleci/project/.circleci/values-staging.yaml \
              --version $HELM_CHART_VERSION \
              --set deployment.version=$CIRCLE_SHA1 \
              simple-staking $HELM_CHART_REPO
      - run:
          name: Release new service version in an atomic way
          command: |
            helm upgrade --install --debug --atomic --wait \
              -n $DEPLOY_STAGING_NAMESPACE --create-namespace \
              --values /home/circleci/project/.circleci/values-staging.yaml \
              --version $HELM_CHART_VERSION \
              --set deployment.version=$CIRCLE_SHA1 \
              simple-staking $HELM_CHART_REPO

  deploy_testnet:
    machine:
      image: ubuntu-2204:2024.01.1
      resource_class: large
    steps:
      - checkout
      - aws-ecr/ecr-login:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          region: "$AWS_REGION"
      - kubernetes/install-kubeconfig:
          kubeconfig: TESTNET_KUBECONFIG
      - helm/install-helm-client
      - run:
          name: Fetch and replace config placeholders from CircleCi env vars
          command: |
            HELM_VALUES=/home/circleci/project/.circleci/values-testnet.yaml
            sed -i "s/API_FQDN/$API_FQDN/g" $HELM_VALUES
            sed -i "s/DASHBOARD_FQDN/$DASHBOARD_FQDN/g" $HELM_VALUES
      - run:
          name: Perform a dry run of the new release
          command: |
            helm upgrade --install --debug --dry-run \
              -n $DEPLOY_TESTNET_NAMESPACE \
              --values /home/circleci/project/.circleci/values-testnet.yaml \
              --version $HELM_CHART_VERSION \
              --set deployment.version=$CIRCLE_SHA1 \
              simple-staking $HELM_CHART_REPO
      - run:
          name: Release new service version in an atomic way
          command: |
            helm upgrade --install --debug --atomic --wait \
              -n $DEPLOY_TESTNET_NAMESPACE --create-namespace \
              --values /home/circleci/project/.circleci/values-testnet.yaml \
              --version $HELM_CHART_VERSION \
              --set deployment.version=$CIRCLE_SHA1 \
              simple-staking $HELM_CHART_REPO

  rollback_testnet:
    machine:
      image: ubuntu-2204:2024.01.1
      resource_class: large
    steps:
      - checkout
      - aws-ecr/ecr-login:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          region: "$AWS_REGION"
      - kubernetes/install-kubeconfig:
          kubeconfig: TESTNET_KUBECONFIG
      - helm/install-helm-client
      - run:
          name: Rollback Helm Chart to previous release
          command: |
            helm rollback --cleanup-on-fail --force --recreate-pods --wait \
              --debug -n $DEPLOY_TESTNET_NAMESPACE simple-staking

workflows:
  CICD:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - push:
          requires:
            - build
              #filters:
              #  tags:
              #    only: /.*/
              #  branches:
              #    only:
              #      - main
      - deploy_staging:
          requires:
            - push
              #filters:
              #  branches:
              #    only:
              #      - main
      - deploy_testnet:
          requires:
            - deploy_staging
      - require_approval_rollback:
          type: approval
          requires:
            - deploy_testnet
          filters:
            branches:
              only:
                - main
      - rollback_testnet:
          requires:
            - require_approval_rollback
