namespace: phase-1-staging
name: simple-staking
deployment:
  image: 490721144737.dkr.ecr.us-east-1.amazonaws.com/simple-staking
  version: REPLACEME
  replicas: 1
  ports:
    - protocol: TCP
      containerPort: 3000
      name: simple-staking
  env:
    - name: MEMPOOL_API
      value: https://babylon.mempool.space
    - name: API_URL
      value: API_STAGING_FQDN
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 1000m
  nodeSelector:
    workload: "staging"
service:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: simple-staking
      name: simple-staking
ingress:
  enabled: true
  tlsCertArn: arn:aws:acm:us-east-2:490721144737:certificate/a18510a6-948f-4595-87d1-e43c8b2e0c8f
  groupName: "testnet3-internal"
  scheme: "internal"
  hosts:
    - host: DASHBOARD_STAGING_FQDN
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ssl-redirect
                port:
                  name: use-annotation
          - path: /
            pathType: Prefix
            backend:
              service:
                name: simple-staking
                port:
                  name: simple-staking
externalDns:
  fqdn: DASHBOARD_STAGING_FQDN
  ttl: 60
purgeCloudflareCache:
  enabled: false
